- lib/patron/session.rb
- spec/session_spec.rb
Allows ```Patron::Session``` to set accessors via constructor hash or block.  
Examples:
***via hash***
```ruby
session = Patron::Session({ :timeout => 20,
:base_url => 'http://localhost:9000',
:headers => {'User-Agent' => 'myapp/1.0'} } )
session.timeout # => 20
session.base_url # => "http://localhost:9000"
session.headers # => {"User-Agent"=>"myapp/1.0"}
```
***via block***
```ruby
session = Patron::Session.new do |patron|
patron.timeout = 20
patron.base_url = 'http://localhost:9000'
patron.headers = {'User-Agent' => 'myapp/1.0'}
end
session.timeout # => 20
session.base_url # => "http://localhost:9000"
session.headers # => {"User-Agent"=>"myapp/1.0"}
```
```bash
rspec spec/session_spec.rb
```
> Adds accessor settings on instantiation via block or hash.

- ext/patron/extconf.rb
- ext/patron/session_ext.c
`rb_thread_blocking_region` is deprecated since 2.0 and completely removed
in 2.2. `rb_thread_call_without_gvl` should be used instead on all rubies
that already have it.
Without this on Ruby 2.2 Patron blocks GVL on every request.
> Use rb_thread_call_without_gvl if possible

- ext/patron/session_ext.c
`cs_list` elements was being comparing incorrectly.
C operator `==` returns 1 on equal elements but SGLIB wants a zero.
As a consequence `ruby_xfree` was being calling on memory regions that are in
use. It caused random segfaults when using Patron.
Also this patch optimizes list element deletion: there is a convenient
SGLIB macro `SGLIB_LIST_DELETE_IF_MEMBER` so there's no need to go
through list twice.
This helped me to get rid of frequent segfaults on my machine (tested on rubies 1.9.3 - 2.2.0). Maybe It's related to #72 but I'm not sure.
> Fix incorrect list element comparator.

- lib/patron/session.rb
If no base_url is given d34837c0d1bac643b05e9f2bc8618006c2b0f932 produces incorrect URIs. 
Example
```ruby
URI.parse(File.join("", "http://localhost")) # => #<URI::Generic /http://localhost>
```
Easiest way to fix this is to add a conditional for the case `base_url.empty?`.
> Fix base url concatenation if base_url is empty

- lib/patron/response.rb
The current version of `Patron::Response#parse_headers` uses regular expressions in two places where they aren't necessary. The first is when splitting `header_data` by CRLF. Changing `split(/\r\n/)` for `split("\r\n")` shows a ten percent improvement when running benchmarks using [`benchmark-ips`](https://github.com/evanphx/benchmark-ips):
```
Calculating -------------------------------------
original     6.530k i/100ms
optimized     8.301k i/100ms
-------------------------------------------------
original     77.486k (±11.8%) i/s -    385.270k
optimized     86.069k (±17.6%) i/s -    415.050k
Comparison:
optimized:    86068.7 i/s
original:    77485.6 i/s - 1.11x slower
```
The second change is that on each iteration the first operation is to check if the line starts with `HTTP/1.[01]` to …
> Optimize Response#parse_headers

- lib/patron/response.rb
- spec/response_spec.rb
Currently patron throws an exception 
```
ArgumentError: unknown encoding name - utf8
```
whenever it encounters response with unknown charset. In my case it fails for charset *utf8* (valid one is *utf-8*)
This PR fixes this problem.
> Don't fail with invalid charset names

- ext/patron/session_ext.c
The curl docs on https://curl.haxx.se/libcurl/c/curl_formadd.html
say that after use the form list should be freed manually
> Ensure the form data is freed in cleanup

- ext/patron/session_ext.c
- spec/session_spec.rb
Replace the data object with return value of its to_s
before performing the request, since string pointers on
non-String VALUE types does not perform any checks but
crashes instead.
Fixes #65
> Cast request body to string when uploading

- ext/patron/session_ext.c
- lib/patron/session.rb
- spec/session_spec.rb
When running repetitive requests (tremendous amounts of repetitive requests in fact), you might want to skip charset detection and header parsing for performance. That is very difficult to do if the class lookup for Response happens at the C level. Therefore, it might be a good idea to use dynamic lookup to figure out the response class. If you subclass Session and override the `response_class` you can then use an optimised version of a Response that, for instance, quickly grabs the status code that you got and moves on.
Adds one method call per request-response cycle and one stack cruby ref, so should be gentle performance-wise.
> RFC: Add the ability to override the Response class by subclassing Session

- ext/patron/session_ext.c
- lib/patron/util.rb
- spec/session_spec.rb
- spec/util_spec.rb
By extension, make escape() and unescape()
available on the Session class so that Util
does not have to have access to the Session
object when performing escapes/unescapes.
> Use CURL URL escaping instead of cgi.rb

- ext/patron/session_ext.c
- lib/patron/request.rb
- lib/patron/session.rb
- spec/session_spec.rb
- spec/support/test_server.rb
using the built-in CURL facilities. CURL will
automatically decode and decompress the response
when Session#automatic_content_encoding is
set to `true`.
Fixes #64
> Add automatic Content-Encoding support

- ext/patron/session_ext.c
- spec/session_spec.rb
Previously the cookie jar would not be saved
even with a cookie jar path set.
Fixes #15
> Fix cookie jar saving after request completion

- spec/response_spec.rb
On 1.9, the file is not assumed to be UTF-8 by default,
so to test with UTF-8 literals the encoding pragma _is_
required.
> Add encoding pragma for testing on 1.9

- ext/patron/session_ext.c
just like in the original header handling code, but for automatic_content_encoding.
Should fix #109, if green a bugfix release (like 6.0.2) would be welcome.
> Add an ifdef guard for CURLOPT_ACCEPT_ENCODING

- ext/patron/session_ext.c
for Session and Request, to honor UAP and to allow easier subclassing of both. This way an object can be provided in lieu of `Patron::Request`, and it will be accepted and treated properly without messing with it's instance variables.
> Replace instance variable gets with reader calls

- ext/patron/session_ext.c
- spec/session_spec.rb
Fix the issue with a timeout occurring when you try to send a literal string buffer as if it were a file. I think something is broken in the session_read_handler just by virtue of it using `strlen()` where binary bodies may be involved. Also, judging from the CURL docs it is really meant for files, or other situations where you fetch from an external source (like an upstream server).
Should resolve #12
> Fix handling of literal PUT bodies larger than 31 byte long (no, really)

- ext/patron/session_ext.c
- spec/session_spec.rb
and remove the read callback function. It may
come back when we implement direct-stream-out
from files later in the development roadmap.
Basically, GETs with a request body require the same fix as #12
> Fix the upload bug with GET bodies as well

- ext/patron/session_ext.c
Fix for issue #119 
Make sure the state->post and stat-last pointers are cleared after
calling curl_formfree(). libcurl does not reset these pointers and they 
need to be cleared.
> Make sure the state->post and stat-last pointers are cleared after curl_formfree()

- CHANGELOG.md
- README.md
- ext/patron/extconf.rb
- spec/session_ssl_spec.rb
There is an issue with libCURL on OSX currently related to a bug (or a subtle behavior quirk) when forking is involved. This documents the issue, adds a test to see if it is present, and adds a compile-time flag to link curl from homebrew explicitly (because Homebrew does not put it in the default $PATH, for reasons).
I am afraid this is the best we can do at the moment. The problem is under investigation upstream.
> Explain the SSL segfaults on OSX and propose a solution

- ext/patron/extconf.rb
to remove double (or even triple) string templating
> Simplify extconf

- patron.gemspec
and recommend an OpenSSL-based libCURL build. I am afraid this is the best we can do ATM, and a post-install message seems the most appropriate to me.
> Add a post-install message for the OSX curl issue

- CHANGELOG.md
- lib/patron.rb
- lib/patron/session.rb
- spec/patron_spec.rb
- spec/session_spec.rb
- spec/spec_helper.rb
I was recently bitten by the fact that Github wants User-Agent to be set, and this was not in my code. I think it is a good idea to set a descriptive header by default, since you can remove it if you want to
sess.headers.delete 'User-Agent'
> Set the default User-Agent

- CHANGELOG.md
- README.md
- ext/patron/session_ext.c
- spec/session_spec.rb
- spec/support/test_server.rb
I think this is going to be a good security-minded check (see the imgur SSRF drama, which involved leading curl to a non-authorised URL by doing a remote-fetch-by-proxy).
> Forbid non-HTTP/HTTPS URLs for requests and do not allow redirect to such URLs

- CHANGELOG.md
- ext/patron/session_ext.c
- lib/patron/session.rb
- spec/session_spec.rb
Allow a simpler way to set a Ruby File object as data argument for performing uploads. This is majorly useful for endpoints that accept verbatim uploads without multipart wrapping. Next step is getting rid of the filename multi-args, but I think it is better to do in 2.0 once we can cut 1.0 because it will have us revamp APIs ;-)
> Allow the `data' argument to put() etc. to be a File

- ext/patron/session_ext.c
It turns out I have swapped the filesize-large and filesize ifdefs in the previous PR. Worthy of a 0.7.1 release too IMO.
> Fix the ifdefs being swapped

- Gemfile
- Gemfile.lock
- Rakefile
- patron.gemspec
Use the latest Bundler/Rubygems features to automate releases.
Once this is applied, all it takes to release Patron is this command:
```
$ bundle exec rake release
```
No dependencies get introduced except for the updated Bundler requirements.
Closes #137
> Update the gem release procedure and gemspec

- CHANGELOG.md
- ext/patron/session_ext.c
- lib/patron/error.rb
- lib/patron/request.rb
- lib/patron/session.rb
- spec/session_ssl_spec.rb
Added support for ssl_version options "TLSv1_0", "TLSv1_1", "TLSv1_2", and "TLSv1_3" with preprocessor sections to allow compilation on systems with older versions of libCURL
Added new option http_version and options "None", "HTTPv1_0", "HTTPv1_1", "HTTPv2_0", "HTTPv2_TLS", and "HTTPv2_PRIOR" with preprocessor sections to allow compilation on systems with older versions of libCURL. 
Added associated error/exceptions for http_version based on the errors for ssl_version.
Ubuntu 16.04 comes with libcurl v7.47.0 tested with that version and the latest 7.54.0
Tested with both versions
"POST /users HTTP/2.0" 200 148 "-" "Patron/Ruby-0.8.0-libcurl/7.54.0 OpenSSL/1.1.0e zlib/1.2.8 nghttp2/1.23.0-DEV librtmp/2.3"
> New libCURL options for HTTP Version and SSL Version

- .travis.yml
- CHANGELOG.md
- ext/patron/session_ext.c
- lib/patron/error.rb
- lib/patron/request.rb
- lib/patron/session.rb
- spec/session_spec.rb
- spec/support/test_server.rb
I thought we could expand on the interrupt handling and add a download size limiter. The rationale is simple: sometimes you want to make sure the server on the other end will not overflow your disk (by mistake or by malice).
Note that I had to switch to Ubuntu 14 on Travis because on their Precise stuff libCURL has a bug that won't let it stop on an interrupt. Same for `Session#interrupt` but there were no tests for that either, so got to add them soon.
> Allow limiting the download size via CURL progress callback

- ext/patron/session_ext.c
- spec/patron_spec.rb
More and more options in Patron depend on the specific CURL features
being available, and that is version dependent. The current libcurl_version
method does not provide something that's easily machine-usable or comparable,
and since these values are available in the included headers we might as well
use them.
Another option would be to use `Gem::Version` but I am not certain libCURL
version semantics are the same as gem version semantics, and then you need
your own comparison operator and so forth. Yet another would be to reuse the CURL_VERSION_NUMERIC define, but it needs bit-twiddling to extract the major/minor/patch versions which is not something very Ruby-esque.
> Add libcurl_version_exact for fetching version

- ext/patron/session_ext.c
- lib/patron/request.rb
- lib/patron/session.rb
- lib/patron/version.rb
- spec/session_spec.rb
- spec/support/test_server.rb
These permit libCURL to time out early if the socket is starved.
This is useful for setting timeouts based on the expected response
size, as opposed to configuring one hard read timeout for the
entire response receive time stretch. For instance, with a read
timeout, you would need to set a value that works equally well
for a 5MB download as well as for a 50MB download.
These two CURLOPTs permit timeouts based on speed as well.
> Add support for LOW_SPEED_TIME and LOW_SPEED_LIMIT

- CHANGELOG.md
- lib/patron/header_parser.rb
- lib/patron/response.rb
- lib/patron/session.rb
- spec/header_parser_spec.rb
- spec/sample_response_headers/headers_wetransfer.txt
- spec/sample_response_headers/headers_wetransfer_with_proxy_status.txt
- spec/sample_response_headers/headers_wetransfer_with_redirect.txt
- spec/sample_response_headers/headers_with_set_cookie.txt
- spec/session_spec.rb
- spec/support/test_server.rb
libCURL passes a string of multiple HTTP responses strung together to
the caller. The caller then has to parse out the separate responses from
that string to get the correct status code etc.
Fixes #152 #153
Fixes lostisland/faraday#733
> Correctly parse headers from multiple responses

- CHANGELOG.md
- ext/patron/session_ext.c
- lib/patron/request.rb
- lib/patron/session.rb
- spec/session_spec.rb
- spec/support/test_server.rb
We should provide some ability for users to re-acquire the GIL and call Ruby callback blocks. We will start with a progress callback which can be used for progress bars and speed computation. We also need to alter the way we unblock the thread so that we correctly handle signals.
This adds the following API:
```
sess.progress_callback = ->(download_total, download_now, upload_total, upload_now) {
progress_bar.update(download_total) # ...or other interesting actions
}
```
The GIL will only be reacquired if this is configured on the Session/Request objects, otherwise we proceed through the same fast path as before with the GIL unlocked.
Closes #150 and paves the way for making #139 possible
> Add Ruby progress callback + customise our GIL unblock function

- CHANGELOG.md
- ext/patron/session_ext.c
- lib/patron/request.rb
- lib/patron/session.rb
- spec/session_spec.rb
We need to be able to change the DNS cache value since our service discovery works on DNS, and clusters get reconfigured fairly often. So it would help if this option were provided.
> Make DNS cache timeout configurable

- CHANGELOG.md
- lib/patron/header_parser.rb
- spec/header_parser_spec.rb
- spec/sample_response_headers/webmock_headers_without_trailing_crlf.txt
Webmock overrides a ton of the Patron session internals, and it furnishes a modified
string of headers to the internal parse_headers method. That string, unlike real libCURL
header strings, does not have the terminating CRLF at the end of the last header. Nor does
it have an empty line at the very end ending with CRLF. This led our parser to return early
since it could not find the string terminator, and the early return in the header parser
code did not return the `responses` array that was already prepared for use. Even though
this is not completely "clean" we will just use a simpler parsing approach without scans.
That said, the expectation that Webmock will keep working with the refactors we appply -
given how much private stuff they rely on - might be a little naive.
Closes #157
> Fix a Webmock regression

- README.md
Homebrew have removed options from the install process, so curl linked to OpenSSL is now a separate formula.
> Update Homebrew install procedure

- .travis.yml
- README.md
- ext/patron/session_ext.c
- patron.gemspec
During a recent investigation we had questions whether
Patron is actually keepalive-friendly. It turned out that
it totally is, but there are a few bits which can be
made less tricky than they were. So:
* Document connection reuse as it is implemented in Patron
* Init the libCURL handle when Session gets created, not lazily
Lazy initialization, although economical, can lead to strange
situations with debugging, and as there already is a lifecycle
we observe (alloc/free via MRI C API) we can just as well init
the libCURL handle there
> Document and clean up connection reuse

- README.md
- ext/patron/extconf.rb
- ext/patron/session_ext.c
- lib/patron/version.rb
On 2.3+ upwards we don't need to check for
header presence as those headers are always
available. We can also unify and simplify
GVL lock/unlock to one set of functions.
> Cleanup older rubies preparing for 1.x

- patron.gemspec
This should make it easier for automated tools to find out what license is used.
> Add licensing information to gemspec.

- lib/patron/request.rb
This PR adds parentheses, in order to avoid Ruby emitting a warning
> `*' interpreted as argument prefix
Hope this helps!
> Avoid Ruby warning `*' interpreted as argument prefix

- patron.gemspec
Perhaps introduced in 02dc7abd8e30b0707f34bc29f91ee3623e4481c1
> gemspec: Avoid a "*spec" typo

- README.md
This PR adds syntax highlighting to the README to improve readability. :sparkles:
> README: Use syntax highlighting code fences

- spec/session_spec.rb
- spec/support/config.ru
We needed to ensure libcurl follows through with forwarding the Range header on
a redirect, and it seems useful to have verified in the specs here as well.
> Add a test for a 307 redirect with a Range header

- .github/workflows/ci.yml
- lib/patron/session.rb
- patron.gemspec
- spec/session_spec.rb
- spec/session_ssl_spec.rb
Migrate CI to GitHub Actions now that Travis CI.org is inactive.
In addition to adding a basic `ci.yml` file, I needed to make several other changes:
1. Loosen the development dependency on `rake` to allow more recent versions
2. Wrap the use of `YAML::load` in the specs in a helper function that allows us to explicitly use `YAML::safe_load` with `OpenStruct` as a permitted class for Ruby 3.1 and up
3. Replace `File.exists?` with `File.exist?`
Ruby head is still failing because of a process start race condition between the `PatronTestServer` and the actual specs.  In the interest of getting something working quickly I temporarily removed `ruby-head`.  All other Rubies in the CI file are green.
> Migrate CI to GitHub actions

- ext/patron/session_ext.c
* Pointer type was incorrect
* Since version 7.82 the curl parameter is ignored, so it's not needed to allocate the handle. See https://curl.se/libcurl/c/curl_easy_escape.html
> Fix session_escape/session_unescape

- spec/spec_helper.rb
- spec/support/fork.rb
3d3d5b3 introduced running Puma processes as child forks.
The fix was necessary but it doesn't monitor the process state properly.
What if `after(:suite)` block is not executed at all and child process becomes a zombie?
What if fork process refuses to exit for some reason?
So I have introduced a `Fork` helper that tries to prevent forks from becoming a zombie by sending it `SIGKILL` if `SIGTERM` didn't have an effect in 500ms or when Ruby interpreter terminates completely (`at_exit`).
> Better monitoring of forked Puma processes

- spec/session_spec.rb
- spec/support/config.ru
sleep 20 is unnecessary big, tests are too slow because of that
> Lower the /slow endpoint respond time

- .github/workflows/ci.yml
- Gemfile
- patron.gemspec
This PR adds Ruby 3.2, 3.3 to test matrix
...and updates actions/checkout to latest release.
...and adds `webrick` to `Gemfile` for testing purposes.
...and chooses rack-2.2 for Ruby 3.3.
<details>
Puma and rack and rackup are running older versions, so they're compatible with older versions of Ruby.
Here, though, we fail: when referring to this code
https://github.com/toland/patron/blob/master/spec/support/config.ru#L129-L145
In 3.3, we fail tests with this:
```
An error occurred while loading ./spec/header_parser_spec.rb.
Failure/Error: APP = Rack::Builder.new { eval(File.read(File.join(__dir__, 'config.ru'))) }
ArgumentError:
wrong number of arguments (given 3, expected 1..2)
```
Aha, that was `        match = Regexp.new("^#{Regexp.quote(location).gsub('/', '/+')}(.*)", nil, 'n')` in …
> CI: add Ruby 3.2, 3.3, and fix builds
